"""update password field length to 350

Revision ID: 63c42965e073
Revises: e6790bfc9bb2
Create Date: 2025-10-20 15:08:50.858256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c42965e073'
down_revision: Union[str, None] = 'e6790bfc9bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_bb_account_master_user_id_fkey', 'tb_bb_account_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_account_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_accounts_user_id_fkey', 'tb_bb_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_accounts', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_activity_logs_user_id_fkey', 'tb_bb_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_activity_logs', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_investments_user_id_fkey', 'tb_bb_investments', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_investments', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_loans_user_id_fkey', 'tb_bb_loans', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_loans', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_money_name_master_user_id_fkey', 'tb_bb_money_name_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_money_name_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_online_payment_name_master_user_id_fkey', 'tb_bb_online_payment_name_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_online_payment_name_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_refresh_tokens_user_id_fkey', 'tb_bb_refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_refresh_tokens', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_statement_details_extract_account_id_fkey', 'tb_bb_statement_details_extract', type_='foreignkey')
    op.drop_constraint('tb_bb_statement_details_extract_user_id_fkey', 'tb_bb_statement_details_extract', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_statement_details_extract', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_statement_details_extract', 'tb_bb_account_master', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_transaction_master_money_name_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.drop_constraint('tb_bb_transaction_master_user_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.drop_constraint('tb_bb_transaction_master_account_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_money_name_master', ['money_name_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_account_master', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_transactions_account_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.drop_constraint('tb_bb_transactions_category_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.drop_constraint('tb_bb_transactions_user_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_accounts', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_categories', ['category_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_user_details_user_id_fkey', 'tb_bb_user_details', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_user_details', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_bb_user_details', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_user_details_user_id_fkey', 'tb_bb_user_details', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_transactions_user_id_fkey', 'tb_bb_transactions', 'tb_bb_users', ['user_id'], ['id'])
    op.create_foreign_key('tb_bb_transactions_category_id_fkey', 'tb_bb_transactions', 'tb_bb_categories', ['category_id'], ['id'])
    op.create_foreign_key('tb_bb_transactions_account_id_fkey', 'tb_bb_transactions', 'tb_bb_accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_transaction_master_account_id_fkey', 'tb_bb_transaction_master', 'tb_bb_account_master', ['account_id'], ['id'])
    op.create_foreign_key('tb_bb_transaction_master_user_id_fkey', 'tb_bb_transaction_master', 'tb_bb_users', ['user_id'], ['id'])
    op.create_foreign_key('tb_bb_transaction_master_money_name_id_fkey', 'tb_bb_transaction_master', 'tb_bb_money_name_master', ['money_name_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_statement_details_extract', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_statement_details_extract', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_statement_details_extract_user_id_fkey', 'tb_bb_statement_details_extract', 'tb_bb_users', ['user_id'], ['id'])
    op.create_foreign_key('tb_bb_statement_details_extract_account_id_fkey', 'tb_bb_statement_details_extract', 'tb_bb_account_master', ['account_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_refresh_tokens', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_refresh_tokens_user_id_fkey', 'tb_bb_refresh_tokens', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_online_payment_name_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_online_payment_name_master_user_id_fkey', 'tb_bb_online_payment_name_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_money_name_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_money_name_master_user_id_fkey', 'tb_bb_money_name_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_loans', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_loans_user_id_fkey', 'tb_bb_loans', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_investments', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_investments_user_id_fkey', 'tb_bb_investments', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_activity_logs', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_activity_logs_user_id_fkey', 'tb_bb_activity_logs', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_accounts', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_accounts_user_id_fkey', 'tb_bb_accounts', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_account_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_account_master_user_id_fkey', 'tb_bb_account_master', 'tb_bb_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
