"""add activity log table

Revision ID: e6790bfc9bb2
Revises: 321b98b4309e
Create Date: 2025-10-20 14:02:09.846034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6790bfc9bb2'
down_revision: Union[str, None] = '321b98b4309e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_bb_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('log_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bb.tb_bb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bb'
    )
    op.create_index(op.f('ix_bb_tb_bb_activity_logs_action'), 'tb_bb_activity_logs', ['action'], unique=False, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_activity_logs_created_at'), 'tb_bb_activity_logs', ['created_at'], unique=False, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_activity_logs_id'), 'tb_bb_activity_logs', ['id'], unique=False, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_activity_logs_user_id'), 'tb_bb_activity_logs', ['user_id'], unique=False, schema='bb')
    op.drop_constraint('tb_bb_account_master_user_id_fkey', 'tb_bb_account_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_account_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_accounts_user_id_fkey', 'tb_bb_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_accounts', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_investments_user_id_fkey', 'tb_bb_investments', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_investments', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_loans_user_id_fkey', 'tb_bb_loans', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_loans', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_money_name_master_user_id_fkey', 'tb_bb_money_name_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_money_name_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_online_payment_name_master_user_id_fkey', 'tb_bb_online_payment_name_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_online_payment_name_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_refresh_tokens_user_id_fkey', 'tb_bb_refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_refresh_tokens', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_statement_details_extract_account_id_fkey', 'tb_bb_statement_details_extract', type_='foreignkey')
    op.drop_constraint('tb_bb_statement_details_extract_user_id_fkey', 'tb_bb_statement_details_extract', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_statement_details_extract', 'tb_bb_account_master', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_statement_details_extract', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_transaction_master_user_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.drop_constraint('tb_bb_transaction_master_account_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.drop_constraint('tb_bb_transaction_master_money_name_id_fkey', 'tb_bb_transaction_master', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_account_master', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transaction_master', 'tb_bb_money_name_master', ['money_name_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_transactions_user_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.drop_constraint('tb_bb_transactions_category_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.drop_constraint('tb_bb_transactions_account_id_fkey', 'tb_bb_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_accounts', ['account_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_categories', ['category_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.create_foreign_key(None, 'tb_bb_transactions', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.drop_constraint('tb_bb_user_details_user_id_fkey', 'tb_bb_user_details', type_='foreignkey')
    op.create_foreign_key(None, 'tb_bb_user_details', 'tb_bb_users', ['user_id'], ['id'], source_schema='bb', referent_schema='bb')
    op.add_column('tb_bb_users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_bb_users', 'role')
    op.drop_constraint(None, 'tb_bb_user_details', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_user_details_user_id_fkey', 'tb_bb_user_details', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transactions', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_transactions_account_id_fkey', 'tb_bb_transactions', 'tb_bb_accounts', ['account_id'], ['id'])
    op.create_foreign_key('tb_bb_transactions_category_id_fkey', 'tb_bb_transactions', 'tb_bb_categories', ['category_id'], ['id'])
    op.create_foreign_key('tb_bb_transactions_user_id_fkey', 'tb_bb_transactions', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_transaction_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_transaction_master_money_name_id_fkey', 'tb_bb_transaction_master', 'tb_bb_money_name_master', ['money_name_id'], ['id'])
    op.create_foreign_key('tb_bb_transaction_master_account_id_fkey', 'tb_bb_transaction_master', 'tb_bb_account_master', ['account_id'], ['id'])
    op.create_foreign_key('tb_bb_transaction_master_user_id_fkey', 'tb_bb_transaction_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_statement_details_extract', schema='bb', type_='foreignkey')
    op.drop_constraint(None, 'tb_bb_statement_details_extract', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_statement_details_extract_user_id_fkey', 'tb_bb_statement_details_extract', 'tb_bb_users', ['user_id'], ['id'])
    op.create_foreign_key('tb_bb_statement_details_extract_account_id_fkey', 'tb_bb_statement_details_extract', 'tb_bb_account_master', ['account_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_refresh_tokens', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_refresh_tokens_user_id_fkey', 'tb_bb_refresh_tokens', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_online_payment_name_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_online_payment_name_master_user_id_fkey', 'tb_bb_online_payment_name_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_money_name_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_money_name_master_user_id_fkey', 'tb_bb_money_name_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_loans', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_loans_user_id_fkey', 'tb_bb_loans', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_investments', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_investments_user_id_fkey', 'tb_bb_investments', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_accounts', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_accounts_user_id_fkey', 'tb_bb_accounts', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tb_bb_account_master', schema='bb', type_='foreignkey')
    op.create_foreign_key('tb_bb_account_master_user_id_fkey', 'tb_bb_account_master', 'tb_bb_users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_bb_tb_bb_activity_logs_user_id'), table_name='tb_bb_activity_logs', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_activity_logs_id'), table_name='tb_bb_activity_logs', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_activity_logs_created_at'), table_name='tb_bb_activity_logs', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_activity_logs_action'), table_name='tb_bb_activity_logs', schema='bb')
    op.drop_table('tb_bb_activity_logs', schema='bb')
    # ### end Alembic commands ###
