"""table creating

Revision ID: 781b5d646d83
Revises: 
Create Date: 2025-10-13 10:23:20.464798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781b5d646d83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_bb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=3), nullable=False),
    sa.Column('display_name', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bb'
    )
    op.create_index(op.f('ix_bb_tb_bb_users_id'), 'tb_bb_users', ['id'], unique=False, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_users_username'), 'tb_bb_users', ['username'], unique=True, schema='bb')
    op.create_table('tb_bb_user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('aadhar_number', sa.String(length=12), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=False),
    sa.Column('address_line1', sa.String(length=100), nullable=True),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bb.tb_bb_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='bb'
    )
    op.create_index(op.f('ix_bb_tb_bb_user_details_aadhar_number'), 'tb_bb_user_details', ['aadhar_number'], unique=True, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_user_details_email'), 'tb_bb_user_details', ['email'], unique=True, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_user_details_id'), 'tb_bb_user_details', ['id'], unique=False, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_user_details_pan_number'), 'tb_bb_user_details', ['pan_number'], unique=True, schema='bb')
    op.create_index(op.f('ix_bb_tb_bb_user_details_phone_number'), 'tb_bb_user_details', ['phone_number'], unique=True, schema='bb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bb_tb_bb_user_details_phone_number'), table_name='tb_bb_user_details', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_user_details_pan_number'), table_name='tb_bb_user_details', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_user_details_id'), table_name='tb_bb_user_details', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_user_details_email'), table_name='tb_bb_user_details', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_user_details_aadhar_number'), table_name='tb_bb_user_details', schema='bb')
    op.drop_table('tb_bb_user_details', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_users_username'), table_name='tb_bb_users', schema='bb')
    op.drop_index(op.f('ix_bb_tb_bb_users_id'), table_name='tb_bb_users', schema='bb')
    op.drop_table('tb_bb_users', schema='bb')
    # ### end Alembic commands ###
